//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.AlbumTags = new HashSet<AlbumTag>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int album_id { get; set; }
        public int album_comments { get; set; }
        public Nullable<System.DateTime> album_date_created { get; set; }
        public Nullable<System.DateTime> album_date_released { get; set; }
        public string album_engineer { get; set; }
        public string album_favorites { get; set; }
        public string album_handle { get; set; }
        public string album_information { get; set; }
        public int album_listens { get; set; }
        public string album_producer { get; set; }
        public string album_title { get; set; }
        public int album_tracks { get; set; }
        public string album_type { get; set; }
        public string album_url { get; set; }
        public Nullable<int> artist_id { get; set; }
    
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumTag> AlbumTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
