//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public int genre_id { get; set; }
        public string genre_color { get; set; }
        public string genre_handle { get; set; }
        public Nullable<int> genre_parent_id { get; set; }
        public string genre_title { get; set; }
    }
}
