//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.Comments = new HashSet<Comment>();
            this.Genres = new HashSet<Genre>();
        }
    
        public int track_id { get; set; }
        public Nullable<int> album_id { get; set; }
        public int artist_id { get; set; }
        public string license_title { get; set; }
        public Nullable<int> track_bit_rate { get; set; }
        public string track_comments { get; set; }
        public string track_composer { get; set; }
        public Nullable<System.DateTime> track_date_created { get; set; }
        public Nullable<System.DateTime> track_date_recorded { get; set; }
        public string track_disc_number { get; set; }
        public string track_duration { get; set; }
        public string track_explicit { get; set; }
        public string track_explicit_notes { get; set; }
        public string track_favorites { get; set; }
        public string track_information { get; set; }
        public string track_instrumental { get; set; }
        public Nullable<int> track_interest { get; set; }
        public string track_language_code { get; set; }
        public Nullable<int> track_listens { get; set; }
        public string track_lyricist { get; set; }
        public string track_number { get; set; }
        public string track_publisher { get; set; }
        public string track_title { get; set; }
        public string track_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
