//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        public int track_id { get; set; }
        public string album_id { get; set; }
        public string album_title { get; set; }
        public string album_url { get; set; }
        public string artist_id { get; set; }
        public string artist_name { get; set; }
        public string artist_url { get; set; }
        public string artist_website { get; set; }
        public string art { get; set; }
        public string license_image_file_large { get; set; }
        public Nullable<int> license_parent_id { get; set; }
        public string license_title { get; set; }
        public string license_url { get; set; }
        public string tags { get; set; }
        public Nullable<int> track_bit_rate { get; set; }
        public string track_comments { get; set; }
        public string track_composer { get; set; }
        public string track_copyright_c { get; set; }
        public string track_copyright_p { get; set; }
        public Nullable<System.DateTime> track_date_created { get; set; }
        public Nullable<System.DateTime> track_date_recorded { get; set; }
        public string track_disc_number { get; set; }
        public string track_duration { get; set; }
        public string track_explicit { get; set; }
        public string track_explicit_notes { get; set; }
        public string track_favorites { get; set; }
        public string track_file { get; set; }
        public string track_genres { get; set; }
        public string track_image_file { get; set; }
        public string track_information { get; set; }
        public string track_instrumental { get; set; }
        public Nullable<int> track_interest { get; set; }
        public string track_language_code { get; set; }
        public Nullable<int> track_listens { get; set; }
        public string track_lyricist { get; set; }
        public string track_number { get; set; }
        public string track_publisher { get; set; }
        public string track_title { get; set; }
        public string track_url { get; set; }
    }
}
