using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using db_music.Models;
using Newtonsoft.Json;
using PagedList;

namespace db_music.Controllers
{
    public class ArtistsController : BaseController
    {
       
        private testEntities db = new testEntities();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.FavoritesSortParam = String.IsNullOrEmpty(sortOrder) ? "favorites_desc" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            /*Main query to gett artists is SELECT TOP(20) FROM Artists 
            This implements pagination to reduce the size of the query when we hit the database, only keeping the first
            20 results that return back from the query built by the following search criteria and order by.
            With pagination, when a user moves to the next page they will load the next twenty results from the query.
            */
            IQueryable<Artist> dbArtists = from a in db.Artists
                            select a;
            if (!String.IsNullOrEmpty(searchString))
            {
                //This is equivalent to SELECT TOP(20) * FROM Artists WHERE Artists.artist_name = searchString
                dbArtists = dbArtists.Where(x => x.artist_name.Contains(searchString));
            }
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            //This logic is equivalent to adding an ORDER BY clause to the query
            switch (sortOrder)
            {
                //ORDER BY artist_name DESC
                case "name_desc":
                    return View(dbArtists.OrderByDescending(s => s.artist_name).ToPagedList(pageNumber, pageSize));
                //ORDER BY favorites
                case "Favorites":
                    return View(dbArtists.OrderBy(s => s.artist_favorites).ToPagedList(pageNumber, pageSize));
                //ORDER BY favorites DESC
                case "favorites_desc":
                    return View(dbArtists.OrderByDescending(s => s.artist_favorites).ToPagedList(pageNumber, pageSize));
                //ORDER BY artist_name
                default:  
                    return View(dbArtists.OrderBy(s => s.artist_name).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Artists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //This is equivalent to SELECT * FROM Artists WHERE artist_id = id
            Artist artist = db.Artists.Find(id);
            var tracks = artist.Tracks;
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }
        [HttpPost]
        public ActionResult AddComment(string CommentText, string CommentRating, string Username, int artist_id)
        {

            /*
             This creates a new comment, and mimics this SQL Query:
             USE [music]
            GO

            INSERT INTO [dbo].[Comments]
                       ([UserId]
                       ,[SongId]
                       ,[AlbumId]
                       ,[TrackId]
                       ,[ArtistId]
                       ,[Text]
                       ,[Rating]
                       ,[Type]
                       ,[Cdate])
                 VALUES
                       Auto Generated by EF
                       ,null
                       ,null
                       ,null
                       ,artist_id
                       ,CommentText
                       ,CommentRating
                       ,Artist
                       ,GETDATE())
            GO
             */

            var newComment = db.Comments.Create();
            newComment.Text = CommentText;
            newComment.Rating = Int32.Parse(CommentRating);
            newComment.UserId = db.Users.Where(x => x.Username == Username).SingleOrDefault().Id;
            newComment.ArtistId = artist_id;
            newComment.Type = "Artist";
            newComment.Cdate = DateTime.Now;
            db.Comments.Add(newComment);
            db.SaveChanges();
            
            return Redirect(Request.UrlReferrer.ToString());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
